# Generated by Django 5.0.3 on 2024-03-20 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario asociado al doctor.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario asociado al paciente.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["company"], name="company_index"),
        ),
    ]
