# Generated by Django 5.0.3 on 2024-04-10 00:37

import apps.base.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario asociado al doctor.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="academic_background",
            field=models.ForeignKey(
                help_text="Formación académica del empleado.",
                limit_choices_to={"type__value": "Formación académica"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_academic_background",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="blood_type",
            field=models.ForeignKey(
                help_text="Tipo de sangre",
                limit_choices_to={"type__value": "Tipo de sangre"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_blood_type",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="clues",
            field=models.ForeignKey(
                help_text="Catálogo de Clave Única de Establecimiento de Salud",
                limit_choices_to={"type__value": "Clues"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_clues",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="federative_entity",
            field=models.ForeignKey(
                help_text="Entidad federativa del empleado.",
                limit_choices_to={"type__value": "Entidad federativa"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_federative_entity",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="indigenous_language",
            field=models.ForeignKey(
                help_text="Lengua indígena del empleado.",
                limit_choices_to={"type__value": "Lengua indígena"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_indigenous_language",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="locality",
            field=models.ForeignKey(
                help_text="Localidad del empleado.",
                limit_choices_to={"type__value": "Localidad"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_locality",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado civil del empleado.",
                limit_choices_to={"type__value": "Estado Civil"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_marital_status",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="municipality",
            field=models.ForeignKey(
                help_text="Municipio del empleado.",
                limit_choices_to={"type__value": "Municipio"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_municipality",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.ForeignKey(
                help_text="Nacionalidad del empleado.",
                limit_choices_to={"type__value": "Nacionalidad"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_nationality",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="religion",
            field=models.ForeignKey(
                help_text="Religión del empleado.",
                limit_choices_to={"type__value": "Religión"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_religion",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="sex",
            field=models.ForeignKey(
                help_text="Sexo del empleado.",
                limit_choices_to={"type__value": "Sexo"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_sex",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="state_of_birth",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado de nacimiento del empleado.",
                limit_choices_to={"type__value": "Entidad federativa"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_by_state_of_birth",
                to="catalog.catalog",
                validators=[apps.base.validators.ActiveValidator()],
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="employee",
            field=models.OneToOneField(
                help_text="Clave Única de Registro de Población.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="employee",
            field=models.OneToOneField(
                help_text="Clave Única de Registro de Población.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario asociado al paciente.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
