# Generated by Django 5.0.3 on 2024-03-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogType",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "value",
                    models.CharField(
                        help_text="Valor del tipo de catálogo. Ejemplo: Estado, Género, etc.",
                        max_length=50,
                        unique=True,
                        verbose_name="Value",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Catálogo",
                "verbose_name_plural": "Tipos de Catálogos",
                "db_table": "catalog_type",
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código del catálogo. Ejemplo: MX, F, etc.",
                        max_length=30,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Valor del catálogo. Ejemplo: México, Femenino, etc.",
                        max_length=255,
                        verbose_name="value",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catálogo padre. Ejemplo: México -> América, Morelia -> Michoacán, etc.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.catalog",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="catalog.catalogtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo",
                "verbose_name_plural": "Catálogos",
                "db_table": "catalog",
            },
        ),
    ]
